version: '2'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_TCP_PORT}:9300"
    mem_limit: ${ES_MEM_LIMIT}
    networks:
      - elk
    environment:
      ES_HEAP_SIZE: 4g
  logstash-indexer:
    image: logstash:${LOGSTASH_VERSION}
    command: logstash -f /etc/logstash/conf.d/
    mem_limit: ${LS_INDEXER_MEM_LIMIT}
    networks:
      - elk
  logstash-shipper:
    image: logstash:${LOGSTASH_VERSION}
    command: logstash -f /etc/logstash/conf.d/
    ports:
      - "${LOGSTASH_SHIPPER_TCP_PORT}:9500"
      - "${LOGSTASH_SHIPPER_UDP_PORT}:9600/udp"
    mem_limit: ${LS_SHIPPER_MEM_LIMIT}
    networks:
      - elk
  kibana:
    build:
      context: ./kibana
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "${KIBANA_PORT}:5601"
    mem_limit: ${KIBANA_MEM_LIMIT}
    networks:
      - elk
