version: '2'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    volumes:
      - ./elasticsearch/config/logging.yml:/usr/share/elasticsearch/config/logging.yml:ro
    mem_limit: ${ES_MEM_LIMIT}
    networks:
      - elk
    environment:
      ES_HEAP_SIZE: 4g
      MAX_LOCKED_MEMORY: unlimited
      MAX_OPEN_FILES: 131070
    ulimits:
      memlock: 9223372036854775807 #2^63 - 1 as unlimited
  logstash-indexer:
    image: logstash:${LOGSTASH_VERSION}
    command: logstash -w 8 -b 250 -f /etc/logstash.conf
    mem_limit: ${LS_INDEXER_MEM_LIMIT}
    networks:
      - elk
  logstash-shipper:
    image: logstash:${LOGSTASH_VERSION}
    command: logstash -w 8 -b 250 -f /etc/logstash.conf
    ports:
      - "${LOGSTASH_SHIPPER_TCP_PORT}:9500"
      - "${LOGSTASH_SHIPPER_UDP_PORT}:9600/udp"
    mem_limit: ${LS_SHIPPER_MEM_LIMIT}
    networks:
      - elk
  kibana:
    build:
      context: ./kibana
    volumes:
      - ./kibana/config/:/opt/kibana/config/:ro
    ports:
      - "${KIBANA_PORT}:5601"
    mem_limit: ${KIBANA_MEM_LIMIT}
    networks:
      - elk
