version: '2'
services:
  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - ${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_TCP_PORT}:9300"
    networks:
      - elk
  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_DATA}:/data
    networks:
      - elk
  logstash-indexer:
    image: logstash:${LOGSTASH_VERSION}
    command: logstash -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/indexer/config:/etc/logstash/conf.d
    links:
      - elasticsearch
      - redis
    networks:
      - elk
  logstash-shipper:
    image: logstash:${LOGSTASH_VERSION}
    command: logstash -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/shipper/config:/etc/logstash/conf.d
    ports:
      - "${LOGSTASH_SHIPPER_TCP_PORT}:9500"
      - "${LOGSTASH_SHIPPER_UDP_PORT}:9600/udp"
    links:
      - redis
    networks:
      - elk
  kibana:
    build: kibana
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "${KIBANA_PORT}:5601"
    links:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge