version: '2'
services:
  elasticsearch:
    extends:
      file: base.yml
      service: elasticsearch
    cpu_shares: 20
    volumes:
      - ${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_TCP_PORT}:9300"
  elasticsearch-slave:
    extends:
      file: base.yml
      service: elasticsearch
    cpu_shares: 20
    volumes:
      - ${ELASTICSEARCH_SLAVE_DATA}:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch-slave.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  logstash-indexer:
    extends:
      file: base.yml
      service: logstash-indexer
    volumes:
      - ./logstash/indexer/ls-redis.conf:/etc/logstash.conf:ro
    links:
      - redis
      - elasticsearch
    cpu_shares: 8
  logstash-shipper:
    extends:
      file: base.yml
      service: logstash-shipper
    volumes:
      - ./logstash/shipper/ls-redis.conf:/etc/logstash.conf:ro
    links:
      - redis
    cpu_shares: 8
  kibana:
    extends:
      file: base.yml
      service: kibana
    links:
      - elasticsearch
    cpu_shares: 2
  redis:
    image: redis:${REDIS_VERSION}
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_DATA}:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    mem_limit: ${REDIS_MEM_LIMIT}
    memswap_limit: ${REDIS_MEM_LIMIT}
    cpu_shares: 2
    restart: always
    networks:
      - elk

networks:
  elk:
    driver: bridge
