version: '2'
services:
  elasticsearch:
    extends:
      file: base.yml
      service: elasticsearch
    cpu_shares: 20
  logstash-indexer:
    extends:
      file: base.yml
      service: logstash-indexer
    volumes:
      - ./logstash/indexer/config-rabbitmq:/etc/logstash/conf.d
    links:
      - rabbitmq
      - elasticsearch
    cpu_shares: 8
  logstash-shipper:
    extends:
      file: base.yml
      service: logstash-shipper
    volumes:
      - ./logstash/shipper/config-rabbitmq:/etc/logstash/conf.d
    links:
      - rabbitmq
    cpu_shares: 8
  kibana:
    extends:
      file: base.yml
      service: kibana
    links:
      - elasticsearch
    cpu_shares: 2
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    volumes:
      - ${RABBITMQ_DATA}:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_MGR_PORT}:15672"
    mem_limit: ${RABBITMQ_MEM_LIMIT}
    cpu_shares: 4
    hostname: rabbitmq.elk
    networks:
      - elk
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

networks:
  elk:
    driver: bridge
