version: '2'
services:
  elasticsearch:
    extends:
      file: base.yml
      service: elasticsearch
    cpu_shares: 20
    volumes:
      - ${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_TCP_PORT}:9300"
  elasticsearch-slave:
    extends:
      file: base.yml
      service: elasticsearch
    cpu_shares: 20
    volumes:
      - ${ELASTICSEARCH_SLAVE_DATA}:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch-slave.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  logstash-indexer:
    extends:
      file: base.yml
      service: logstash-indexer
    volumes:
      - ./logstash/indexer/ls-rabbitmq.conf:/etc/logstash.conf:ro
    links:
      - rabbitmq
      - elasticsearch
    cpu_shares: 8
  logstash-shipper:
    extends:
      file: base.yml
      service: logstash-shipper
    volumes:
      - ./logstash/shipper/ls-rabbitmq.conf:/etc/logstash.conf:ro
    links:
      - rabbitmq
    cpu_shares: 8
  kibana:
    extends:
      file: base.yml
      service: kibana
    links:
      - elasticsearch
    cpu_shares: 2
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    volumes:
      - ${RABBITMQ_DATA}:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_MGR_PORT}:15672"
    mem_limit: ${RABBITMQ_MEM_LIMIT}
    memswap_limit: ${RABBITMQ_MEM_LIMIT}
    cpu_shares: 4
    restart: always
    hostname: rabbitmq.elk
    networks:
      - elk
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

networks:
  elk:
    driver: bridge
