version: '2'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_TCP_PORT}:9300"
    mem_limit: ${ES_MEM_LIMIT}
    networks:
      - elk
    environment:
      ES_HEAP_SIZE: 4g
  redis:
    image: redis:${REDIS_VERSION}
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_DATA}:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    mem_limit: ${REDIS_MEM_LIMIT}
    networks:
      - elk
  logstash-indexer:
    image: logstash:${LOGSTASH_VERSION}
    command: logstash -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/indexer/config:/etc/logstash/conf.d
    links:
      - elasticsearch
      - redis
    mem_limit: ${LOGSTASH_INDEXER_MEM_LIMIT}
    networks:
      - elk
  logstash-shipper:
    image: logstash:${LOGSTASH_VERSION}
    command: logstash -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/shipper/config:/etc/logstash/conf.d
    ports:
      - "${LOGSTASH_SHIPPER_TCP_PORT}:9500"
      - "${LOGSTASH_SHIPPER_UDP_PORT}:9600/udp"
    links:
      - redis
    mem_limit: ${LOGSTASH_SHIPPER_MEM_LIMIT}
    networks:
      - elk
  kibana:
    build:
      context: ./kibana
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "${KIBANA_PORT}:5601"
    links:
      - elasticsearch
    mem_limit: ${KIBANA_MEM_LIMIT}
    networks:
      - elk

networks:
  elk:
    driver: bridge
